### ISSUE TITLE
sectionTitles  not show  on iOS 10

### ISSUE THREAD

**Issue by hhfa** [HeshamMegid/HMSegmentedControl#219] opened 2016-09-13 05:33 UTC
sectionTitles  not show  on iOS 10

**Comment by bingbingBang** [comment] 2016-09-14 03:05
same issue with #215

**Comment by Leon-OS** [comment] 2016-09-14 08:34
iOS10：one or two words is not show，but sectionTitles words number than three, is show normal.
quickly: add ' ' at word head and foot. "ok" --> " ok "

**Comment by ricsantos** [comment] 2016-09-15 05:29
This is a duplicate of #215

**Comment by HeshamMegid** [comment] 2016-09-17 17:32
This has been fixed in the latest version. Please check it out.

**Closed by HeshamMegid** 2016-09-17 17:32 UTC
