### ISSUE TITLE
sectionsTitle still can't show when the system is up ios 10.0 ,as the ststem is ios 10.0.1

### ISSUE THREAD

**Issue by heiseyoumosjm** [HeshamMegid/HMSegmentedControl#221] opened 2016-09-15 01:15 UTC
sectionsTitle still can't show when the system is up ios 10.0 ,as the ststem is ios 10.0.1

**Comment by damthieuquang** [comment] 2016-09-15 02:34
@HeshamMegid 
SegmentedController works well with iOS 9 and lower but in iOS 10 it has a problem
![screen shot 2016-09-15 at 9 31 31 am](https://cloud.githubusercontent.com/assets/6957056/18536437/88f9b4de-7b27-11e6-8ab4-36b8cdb645c6.png)

**Comment by ricsantos** [comment] 2016-09-15 05:29
This is a duplicate of #215

**Comment by HeshamMegid** [comment] 2016-09-17 17:26
This issue has been fixed. Please update to the latest release.

**Closed by HeshamMegid** 2016-09-17 17:26 UTC
