### ISSUE TITLE
ios10 title does not show

### ISSUE THREAD

**Issue by VolitationXiaoXing** [HeshamMegid/HMSegmentedControl#237] opened 2016-10-08 11:19 UTC

**Comment by igiu1988** [comment] 2016-10-09 02:05
I'm ok now, so please show more code, let's see what happens~

**Comment by notonly** [comment] 2016-10-09 03:00
#222 This will help.

**Comment by mickeyl** [comment] 2016-10-20 15:05
This is a duplicate of #222, so feel free to close it.

**Closed** 2016-11-04 15:37 UTC
