### ISSUE TITLE
This is a serious error

### ISSUE THREAD

**Issue by msmq** [HeshamMegid/HMSegmentedControl#91] opened 2015-02-25 13:54 UTC
Hi,

On iOS 7.1, i am getting this error:

<Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update

Please fix it or suggest me what i need to do for it? Thanks

**Comment by gerardp** [comment] 2015-03-03 13:37
+1
I have the same error!

**Comment by HeshamMegid** [comment] 2015-03-03 14:00
Closing this as a duplicate of #87.

**Closed by HeshamMegid** 2015-03-03 14:00 UTC

**Comment by yagneshGingercube** [comment] 2015-03-03 15:29
I had the same issue while using setTitleFormatter which returns NSAttributedString. To fix this issue , I pass CGColor (not UIColor) in the attributes for NSAttributedString. 

NSAttributedString *attString = [[NSAttributedString alloc] initWithString:title attributes:@{NSForegroundColorAttributeName:(__bridge id)[UIColor blueColor].CGColor}];
