### ISSUE TITLE
<Error>: CGContextSetStrokeColorWithColor: invalid context 0x0

### ISSUE THREAD

**Issue by purkylin** [HeshamMegid/HMSegmentedControl#87] opened 2015-02-07 07:55 UTC
Environment: Ipad3, ios7

<Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by hugocroch** [comment] 2015-02-11 19:25
I have the same message on iOS 7 on a iPhone 5c. But it is probably the same result on any device.

**Comment by gerardp** [comment] 2015-03-03 13:39
+1
I have the same error!

**Comment by HeshamMegid** [comment] 2015-03-03 13:57
I'm aware of this but I haven't found a fix yet. Pull requests would be appreciated.

**Comment by foxluqi** [comment] 2015-03-04 03:19
![2015-03-04 11 08 58](https://cloud.githubusercontent.com/assets/5027825/6477557/c70a0f1c-c25f-11e4-8661-8ac70e710c59.png)

I added symbol break of 'CGPostError' and dumped above log. Hope it help.
I think the issue is only happened in iOS7.

**Comment by foxluqi** [comment] 2015-03-04 03:47
And I traced the error from below statement
titleLayer.string = [self attributedTitleAtIndex:idx];
And set NSForegroundColorAttributeName attribute string causes CG error.

**Comment by foxluqi** [comment] 2015-03-04 07:15
Same issues
http://stackoverflow.com/questions/11728307/nsmutableattributedstring-nsforegroundcolorattributename
http://stackoverflow.com/questions/26980836/ios-7-nsattributedstring-nsforegroundcolorattributename-attribute-set-to-white

**Comment by HeshamMegid** [comment] 2015-03-11 20:38
This should be fixed in d8e6e4a14024309b6a9c68286d60cf660e4d342b

**Closed by HeshamMegid** 2015-03-11 20:38 UTC
